const methods = [
    "focus-direction",
    "focus-recent-workspace",
    "focus-next-workspace",
    "focus-previous-workspace",
    "focus-named-workspace",
    "move-direction",
    "move-to-recent-workspace",
    "move-to-next-workspace",
    "move-to-previous-workspace",
    "move-to-named-workspace",
    "move-workspace-direction",
    "resize-window",
    "close-window",
    "ignore-window",
    "toggle-tiling-direction",
    "toggle-floating",
    "toogle-minimized",
    "toggle-fullscreen",
    "toogle-tiling",
    "set-floating",
    "set-minimized",
    "set-fullscreen",
    "set-tiling",
    "exit",
    "reload-config",
    "redraw",
    "enable-binding-mode",
    "disable-binding-mode",
] as const;
export type Methods = (typeof methods)[number];
